name: Exercism Kotlin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Diamond
      run: cd kotlin/diamond && chmod +x ./gradlew && ./gradlew test
    - name: Gigasecond
      run: cd kotlin/gigasecond && chmod +x ./gradlew && ./gradlew test
    - name: Hamming
      run: cd kotlin/hamming && chmod +x ./gradlew && ./gradlew test
    - name: Hello World
      run: cd kotlin/hello-world && chmod +x ./gradlew && ./gradlew test
    - name: Isogram
      run: cd kotlin/isogram && chmod +x ./gradlew && ./gradlew test
    - name: Leap
      run: cd kotlin/leap && chmod +x ./gradlew && ./gradlew test
    - name: Pangram
      run: cd kotlin/pangram && chmod +x ./gradlew && ./gradlew test
    - name: Pig-latin
      run: cd kotlin/pig-latin && chmod +x ./gradlew && ./gradlew test
    - name: Raindrops
      run: cd kotlin/raindrops && chmod +x ./gradlew && ./gradlew test
    - name: Reverse-string
      run: cd kotlin/reverse-string && chmod +x ./gradlew && ./gradlew test
    - name: Scrabble-score
      run: cd kotlin/scrabble-score && chmod +x ./gradlew && ./gradlew test
    - name: Two-fer
      run: cd kotlin/two-fer && chmod +x ./gradlew && ./gradlew test
