name: Exercism Kotlin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Diamond
      run: cd diamond && chmod +x ./gradlew && ./gradlew test
    - name: Gigasecond
      run: cd gigasecond && chmod +x ./gradlew && ./gradlew test
    - name: Hamming
      run: cd hamming && chmod +x ./gradlew && ./gradlew test
    - name: Hello World
      run: cd hello-world && chmod +x ./gradlew && ./gradlew test
    - name: Isogram
      run: cd isogram && chmod +x ./gradlew && ./gradlew test
    - name: Pangram
      run: cd pangram && chmod +x ./gradlew && ./gradlew test
    - name: Pig-latin
      run: cd pig-latin && chmod +x ./gradlew && ./gradlew test
    - name: Raindrops
      run: cd raindrops && chmod +x ./gradlew && ./gradlew test
    - name: Reverse-string
      run: cd reverse-string && chmod +x ./gradlew && ./gradlew test
    - name: Two-fer
      run: cd two-fer && chmod +x ./gradlew && ./gradlew test
